require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VaccinationsController do

  # This should return the minimal set of attributes required to create a valid
  # Vaccination. As you add validations to Vaccination, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VaccinationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vaccinations as @vaccinations" do
      vaccination = Vaccination.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vaccinations).should eq([vaccination])
    end
  end

  describe "GET show" do
    it "assigns the requested vaccination as @vaccination" do
      vaccination = Vaccination.create! valid_attributes
      get :show, {:id => vaccination.to_param}, valid_session
      assigns(:vaccination).should eq(vaccination)
    end
  end

  describe "GET new" do
    it "assigns a new vaccination as @vaccination" do
      get :new, {}, valid_session
      assigns(:vaccination).should be_a_new(Vaccination)
    end
  end

  describe "GET edit" do
    it "assigns the requested vaccination as @vaccination" do
      vaccination = Vaccination.create! valid_attributes
      get :edit, {:id => vaccination.to_param}, valid_session
      assigns(:vaccination).should eq(vaccination)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vaccination" do
        expect {
          post :create, {:vaccination => valid_attributes}, valid_session
        }.to change(Vaccination, :count).by(1)
      end

      it "assigns a newly created vaccination as @vaccination" do
        post :create, {:vaccination => valid_attributes}, valid_session
        assigns(:vaccination).should be_a(Vaccination)
        assigns(:vaccination).should be_persisted
      end

      it "redirects to the created vaccination" do
        post :create, {:vaccination => valid_attributes}, valid_session
        response.should redirect_to(Vaccination.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vaccination as @vaccination" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vaccination.any_instance.stub(:save).and_return(false)
        post :create, {:vaccination => {}}, valid_session
        assigns(:vaccination).should be_a_new(Vaccination)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vaccination.any_instance.stub(:save).and_return(false)
        post :create, {:vaccination => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vaccination" do
        vaccination = Vaccination.create! valid_attributes
        # Assuming there are no other vaccinations in the database, this
        # specifies that the Vaccination created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vaccination.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => vaccination.to_param, :vaccination => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested vaccination as @vaccination" do
        vaccination = Vaccination.create! valid_attributes
        put :update, {:id => vaccination.to_param, :vaccination => valid_attributes}, valid_session
        assigns(:vaccination).should eq(vaccination)
      end

      it "redirects to the vaccination" do
        vaccination = Vaccination.create! valid_attributes
        put :update, {:id => vaccination.to_param, :vaccination => valid_attributes}, valid_session
        response.should redirect_to(vaccination)
      end
    end

    describe "with invalid params" do
      it "assigns the vaccination as @vaccination" do
        vaccination = Vaccination.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vaccination.any_instance.stub(:save).and_return(false)
        put :update, {:id => vaccination.to_param, :vaccination => {}}, valid_session
        assigns(:vaccination).should eq(vaccination)
      end

      it "re-renders the 'edit' template" do
        vaccination = Vaccination.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vaccination.any_instance.stub(:save).and_return(false)
        put :update, {:id => vaccination.to_param, :vaccination => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vaccination" do
      vaccination = Vaccination.create! valid_attributes
      expect {
        delete :destroy, {:id => vaccination.to_param}, valid_session
      }.to change(Vaccination, :count).by(-1)
    end

    it "redirects to the vaccinations list" do
      vaccination = Vaccination.create! valid_attributes
      delete :destroy, {:id => vaccination.to_param}, valid_session
      response.should redirect_to(vaccinations_url)
    end
  end

end
