require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VaccinesController do

  # This should return the minimal set of attributes required to create a valid
  # Vaccine. As you add validations to Vaccine, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VaccinesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vaccines as @vaccines" do
      vaccine = Vaccine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vaccines).should eq([vaccine])
    end
  end

  describe "GET show" do
    it "assigns the requested vaccine as @vaccine" do
      vaccine = Vaccine.create! valid_attributes
      get :show, {:id => vaccine.to_param}, valid_session
      assigns(:vaccine).should eq(vaccine)
    end
  end

  describe "GET new" do
    it "assigns a new vaccine as @vaccine" do
      get :new, {}, valid_session
      assigns(:vaccine).should be_a_new(Vaccine)
    end
  end

  describe "GET edit" do
    it "assigns the requested vaccine as @vaccine" do
      vaccine = Vaccine.create! valid_attributes
      get :edit, {:id => vaccine.to_param}, valid_session
      assigns(:vaccine).should eq(vaccine)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vaccine" do
        expect {
          post :create, {:vaccine => valid_attributes}, valid_session
        }.to change(Vaccine, :count).by(1)
      end

      it "assigns a newly created vaccine as @vaccine" do
        post :create, {:vaccine => valid_attributes}, valid_session
        assigns(:vaccine).should be_a(Vaccine)
        assigns(:vaccine).should be_persisted
      end

      it "redirects to the created vaccine" do
        post :create, {:vaccine => valid_attributes}, valid_session
        response.should redirect_to(Vaccine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vaccine as @vaccine" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vaccine.any_instance.stub(:save).and_return(false)
        post :create, {:vaccine => {}}, valid_session
        assigns(:vaccine).should be_a_new(Vaccine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vaccine.any_instance.stub(:save).and_return(false)
        post :create, {:vaccine => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vaccine" do
        vaccine = Vaccine.create! valid_attributes
        # Assuming there are no other vaccines in the database, this
        # specifies that the Vaccine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vaccine.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => vaccine.to_param, :vaccine => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested vaccine as @vaccine" do
        vaccine = Vaccine.create! valid_attributes
        put :update, {:id => vaccine.to_param, :vaccine => valid_attributes}, valid_session
        assigns(:vaccine).should eq(vaccine)
      end

      it "redirects to the vaccine" do
        vaccine = Vaccine.create! valid_attributes
        put :update, {:id => vaccine.to_param, :vaccine => valid_attributes}, valid_session
        response.should redirect_to(vaccine)
      end
    end

    describe "with invalid params" do
      it "assigns the vaccine as @vaccine" do
        vaccine = Vaccine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vaccine.any_instance.stub(:save).and_return(false)
        put :update, {:id => vaccine.to_param, :vaccine => {}}, valid_session
        assigns(:vaccine).should eq(vaccine)
      end

      it "re-renders the 'edit' template" do
        vaccine = Vaccine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vaccine.any_instance.stub(:save).and_return(false)
        put :update, {:id => vaccine.to_param, :vaccine => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vaccine" do
      vaccine = Vaccine.create! valid_attributes
      expect {
        delete :destroy, {:id => vaccine.to_param}, valid_session
      }.to change(Vaccine, :count).by(-1)
    end

    it "redirects to the vaccines list" do
      vaccine = Vaccine.create! valid_attributes
      delete :destroy, {:id => vaccine.to_param}, valid_session
      response.should redirect_to(vaccines_url)
    end
  end

end
